# Generated by Django 5.1.7 on 2025-03-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('Empresa', 'empresa'), ('EPM', 'Empresas publicas de Medellin')], default='EPM', max_length=50)),
                ('month', models.PositiveSmallIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
