# Generated by Django 5.1.7 on 2025-03-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consume',
            name='company',
        ),
    ]
